version: "3.7"

services:

  explorer:
    container_name: strat-explorer
    image: blockcore/explorer:0.0.7
    environment:
      VIRTUAL_HOST: strat.explorer.blockcore.net
      VIRTUAL_PORT: 9911
      VIRTUAL_NETWORK: proxy
      LETSENCRYPT_HOST: strat.explorer.blockcore.net
      LETSENCRYPT_EMAIL: admin@blockcore.net
    command: ["--chain=STRAT"]
    restart: always