version: "3.7"

volumes:
  database:
    name: strat-db
  blockchain:
    name: strat-data

services:

  indexer:
    container_name: strat-indexer
    networks:
      indexer:
        ipv4_address: 172.16.12.10
    image: blockcore/indexer:0.0.5
    environment:
      VIRTUAL_HOST: strat.indexer.blockcore.net
      VIRTUAL_PORT: 9910
      VIRTUAL_NETWORK: proxy
      LETSENCRYPT_HOST: strat.indexer.blockcore.net
      LETSENCRYPT_EMAIL: admin@blockcore.net
    command: ["--chain=STRAT"]
    restart: always
    depends_on:
        - mongo
        - chain

  chain:
    container_name: strat-chain
    image: blockcore/node-strat:1.0.9
    command: ["-server=1", "-txindex=1", "-rpcallowip=172.16.12.10", "-rpcbind=strat-chain", "-apiuri=http://0.0.0.0:37221", "-rpcuser=rpcuser", "-rpcpassword=rpcpassword"]
    restart: always
    stop_grace_period: 15m
    networks:
      - indexer
    volumes:
      - blockchain:/root/.blockcore
    ports:
      - 16178:16178

  mongo:
    container_name: strat-mongo
    image: mongo:3.4
    restart: always
    stop_grace_period: 5m
    networks:
      - indexer
    volumes:
      - database:/data/db
      - database:/data/configdb

networks:
  indexer:
    name: strat-network
    ipam:
      config:
        - subnet: 172.16.12.0/28