version: "2.4"

services:

  explorer:
    container_name: xds-explorer
    image: blockcore/explorer:0.1.4
    environment:
      VIRTUAL_HOST: xds.explorer.blockcore.net
      VIRTUAL_PORT: 9911
      VIRTUAL_NETWORK: proxy
      LETSENCRYPT_HOST: xds.explorer.blockcore.net
      LETSENCRYPT_EMAIL: admin@blockcore.net
    command: ["--chain=XDS"]
    restart: always
