version: "3.7"

volumes:
  database:
    name: xds-db
  blockchain:
    name: xds-data

services:

  indexer:
    container_name: xds-indexer
    networks:
      indexer:
        ipv4_address: 172.16.11.10
    image: blockcore/indexer:0.0.4
    environment:
      VIRTUAL_HOST: xds.indexer.blockcore.net
      VIRTUAL_PORT: 9910
      VIRTUAL_NETWORK: proxy
      LETSENCRYPT_HOST: xds.indexer.blockcore.net
      LETSENCRYPT_EMAIL: admin@blockcore.net
    command: ["--chain=XDS"]
    restart: always
    depends_on:
        - mongo
        - chain

  chain:
    container_name: xds-chain
    image: blockcore/node-xds:1.0.4
    command: ["-server=1", "-txindex=1", "-rpcallowip=172.16.11.10", "-rpcbind=xds-chain", "-apiuri=http://0.0.0.0:48334", "-rpcuser=rpcuser", "-rpcpassword=rpcpassword"]
    restart: always
    stop_grace_period: 15m
    networks:
      - indexer
    volumes:
      - blockchain:/root/.xds

  mongo:
    container_name: xds-mongo
    image: mongo:3.4
    restart: always
    stop_grace_period: 5m
    networks:
      - indexer
    volumes:
      - database:/data/db
      - database:/data/configdb

networks:
  indexer:
    name: xds-network
    ipam:
      config:
        - subnet: 172.16.11.0/28