version: "2.4"

volumes:
  database:
    name: xlr-db
  blockchain:
    name: xlr-data

services:

  indexer:
    container_name: xlr-indexer
    networks:
      indexer:
        ipv4_address: 172.16.13.10
    image: blockcore/indexer:0.1.22
    environment:
      VIRTUAL_HOST: xlr.indexer.blockcore.net
      VIRTUAL_PORT: 9910
      VIRTUAL_NETWORK: proxy
      LETSENCRYPT_HOST: xlr.indexer.blockcore.net
      LETSENCRYPT_EMAIL: admin@blockcore.net
      ASPNETCORE_URLS: https://*:9910
    command: ["--chain=XLR"]
    restart: unless-stopped
    depends_on:
        - mongo
        - chain

  chain:
    container_name: xlr-chain
    image: blockcore/node-multi:1.1.34
    command: ["--chain=XLR", "-server=1", "-addnode=80.211.88.141", "-txindex=1", "-rpcallowip=172.16.13.10", "-rpcbind=xlr-chain", "-apiuri=http://0.0.0.0:62008", "-rpcuser=rpcuser", "-rpcpassword=rpcpassword"]
    restart: unless-stopped
    stop_grace_period: 15m
    volumes:
      - blockchain:/root/.blockcore
    ports:
      - 60008:60008

  mongo:
    container_name: xlr-mongo
    image: mongo:5.0.5
    command: "--wiredTigerCacheSizeGB 1"
    mem_limit: 1000m
    restart: unless-stopped
    stop_grace_period: 5m
    volumes:
      - database:/data/db
      - database:/data/configdb
