version: "2.4"

volumes:
  database:
    name: homecoin-db
  blockchain:
    name: homecoin-data
  tipbot-blockchain:
    name: homecoin-tipbot-data
  tipbot-database:
    name: homecoin-tipbot-db

services:

  explorer:
    container_name: homecoin-explorer
    image: blockcore/explorer:0.1.14
    environment:
      VIRTUAL_HOST: homecoin.explorer.blockcore.net
      VIRTUAL_PORT: 9911
      VIRTUAL_NETWORK: proxy
      LETSENCRYPT_HOST: homecoin.explorer.blockcore.net
      LETSENCRYPT_EMAIL: admin@blockcore.net
    command: ["--chain=HOME"]
    restart: unless-stopped

  indexer:
    container_name: homecoin-indexer
    image: blockcore/indexer:0.1.22
    environment:
      VIRTUAL_HOST: homecoin.indexer.blockcore.net
      VIRTUAL_PORT: 9910
      VIRTUAL_NETWORK: proxy
      LETSENCRYPT_HOST: homecoin.indexer.blockcore.net
      LETSENCRYPT_EMAIL: admin@blockcore.net
      ASPNETCORE_URLS: https://*:9910
    command: ["--chain=HOME"]
    restart: unless-stopped
    depends_on:
        - mongo
        - chain

  chain:
    container_name: homecoin-chain
    image: blockcore/node-homecoin:1.0.29
    command: ["-server=1", "-txindex=1", "-iprangefiltering=0", "-rpcallowip=192.168.0.0/8", "-rpcallowip=172.0.0.0/8", "-rpcbind=0.0.0.0", "-apiuri=http://0.0.0.0:33333", "-rpcuser=rpcuser", "-rpcpassword=rpcpassword"]
    restart: unless-stopped
    stop_grace_period: 15m
    volumes:
      - blockchain:/root/.blockcore
    ports:
      - 33331:33331 # Make this a public node.

  mongo:
    container_name: homecoin-mongo
    image: mongo:5.0.5
    command: "--wiredTigerCacheSizeGB 1.5"
    mem_limit: 1500m
    restart: unless-stopped
    stop_grace_period: 5m
    volumes:
      - database:/data/db
      - database:/data/configdb

  tipbot:
    container_name: homecoin-tipbot
    image: blockcore/tipbot:0.0.3
    env_file:
      - tipbot.env
    command: ["--chain=HOME"]
    restart: unless-stopped
    depends_on:
        - tipbot-database
        - tipbot-chain
    
  tipbot-chain:
    container_name: homecoin-tipbot-chain
    image: blockcore/node-homecoin:1.0.29
    command: ["-server=1", "-txindex=0", "-iprangefiltering=0", "-rpcallowip=192.168.0.0/8", "-rpcallowip=172.0.0.0/8", "-rpcbind=0.0.0.0", "-apiuri=http://0.0.0.0:33333", "-rpcuser=rpcuser", "-rpcpassword=rpcpassword"]
    restart: unless-stopped
    stop_grace_period: 15m
    volumes:
      - tipbot-blockchain:/root/.blockcore

  tipbot-database:
    container_name: homecoin-tipbot-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    env_file:
      - tipbot.env
    environment:
      ACCEPT_EULA: "Y"
    restart: unless-stopped
    volumes:
      - tipbot-database:/var/opt/mssql
