version: "2.4"

volumes:
  database:
    name: sbc-db
  blockchain:
    name: sbc-data
  tipbot-blockchain:
    name: sbc-tipbot-data
  tipbot-database:
    name: sbc-tipbot-db

services:

  explorer:
    container_name: sbc-explorer
    image: blockcore/explorer:0.1.13
    environment:
      VIRTUAL_HOST: sbc.explorer.blockcore.net
      VIRTUAL_PORT: 9911
      VIRTUAL_NETWORK: proxy
      LETSENCRYPT_HOST: sbc.explorer.blockcore.net
      LETSENCRYPT_EMAIL: admin@blockcore.net
    command: ["--chain=SBC"]
    restart: unless-stopped

  indexer:
    container_name: sbc-indexer
    image: blockcore/indexer:0.1.20
    environment:
      VIRTUAL_HOST: sbc.indexer.blockcore.net
      VIRTUAL_PORT: 9910
      VIRTUAL_NETWORK: proxy
      LETSENCRYPT_HOST: sbc.indexer.blockcore.net
      LETSENCRYPT_EMAIL: admin@blockcore.net
      ASPNETCORE_URLS: https://*:9910
    command: ["--chain=SBC"]
    restart: unless-stopped
    depends_on:
        - mongo
        - chain

  chain:
    container_name: sbc-chain
    image: blockcore/node-multi:1.1.32
    command: ["--chain=SBC", "-server=1", "-txindex=1", "-iprangefiltering=0", "-rpcallowip=192.168.0.0/8", "-rpcallowip=172.0.0.0/8", "-rpcbind=0.0.0.0", "-apiuri=http://0.0.0.0:15008", "-rpcuser=rpcuser", "-rpcpassword=rpcpassword"]
    restart: unless-stopped
    stop_grace_period: 15m
    volumes:
      - blockchain:/root/.blockcore
    ports:
      - 15006:15006 # Make this a public node.

  mongo:
    container_name: sbc-mongo
    image: mongo:5.0.5
    command: "--wiredTigerCacheSizeGB 1.5"
    mem_limit: 1500m
    restart: unless-stopped
    stop_grace_period: 5m
    volumes:
      - database:/data/db
      - database:/data/configdb

  # tipbot:
  #   container_name: sbc-tipbot
  #   image: blockcore/tipbot:0.0.7
  #   env_file:
  #     - tipbot.env
  #   command: ["--chain=SBC"]
  #   restart: unless-stopped
  #   depends_on:
  #       - tipbot-database
  #       - tipbot-chain
    
  # tipbot-chain:
  #   container_name: sbc-tipbot-chain
  #   image: blockcore/node-multi:1.1.32
  #   command: ["--chain=SBC", "-server=1", "-txindex=0", "-iprangefiltering=0", "-rpcallowip=192.168.0.0/8", "-rpcallowip=172.0.0.0/8", "-rpcbind=0.0.0.0", "-apiuri=http://0.0.0.0:15008", "-rpcuser=rpcuser", "-rpcpassword=rpcpassword"]
  #   restart: unless-stopped
  #   stop_grace_period: 15m
  #   volumes:
  #     - tipbot-blockchain:/root/.blockcore

  # tipbot-database:
  #   container_name: sbc-tipbot-db
  #   image: mcr.microsoft.com/mssql/server:2019-latest
  #   env_file:
  #     - tipbot.env
  #   environment:
  #     ACCEPT_EULA: "Y"
  #   restart: unless-stopped
  #   volumes:
  #     - tipbot-database:/var/opt/mssql
