version: "2.4"

services:

  explorer:
    container_name: ${PREFIX}-explorer
    image: blockcore/explorer:0.1.12
    environment:
      VIRTUAL_HOST: ${DOMAIN}
      VIRTUAL_PORT: 9911
      VIRTUAL_NETWORK: proxy
      LETSENCRYPT_HOST: ${DOMAIN}
      LETSENCRYPT_EMAIL: ${EMAIL}
    command: ["--chain=${CHAIN}"]
    restart: always