version: "2.4"

services:

  explorer:
    container_name: blockcore-paperwallet
    image: nginx
    environment:
      VIRTUAL_HOST: paperwallet.blockcore.net
      VIRTUAL_PORT: 80
      VIRTUAL_NETWORK: proxy
      LETSENCRYPT_HOST: paperwallet.blockcore.net
      LETSENCRYPT_EMAIL: admin@blockcore.net
    restart: always
    volumes:
      - /home/blockcore/src/blockcore-paperwallet:/usr/share/nginx/html
    # ports:
    #   - 8088:80