version: "2.4"

volumes:
  database:
    name: strax-db
  blockchain:
    name: strax-data
  tipbot-blockchain:
    name: strax-tipbot-data
  tipbot-database:
    name: strax-tipbot-db

services:

  explorer:
    container_name: strax-explorer
    image: blockcore/explorer:0.1.12
    environment:
      VIRTUAL_HOST: strax.explorer.blockcore.net
      VIRTUAL_PORT: 9911
      VIRTUAL_NETWORK: proxy
      LETSENCRYPT_HOST: strax.explorer.blockcore.net
      LETSENCRYPT_EMAIL: admin@blockcore.net
    command: ["--chain=STRAX"]
    restart: unless-stopped

  indexer:
    container_name: strax-indexer
    image: blockcore/indexer:0.1.20
    environment:
      VIRTUAL_HOST: strax.indexer.blockcore.net
      VIRTUAL_PORT: 9910
      VIRTUAL_NETWORK: proxy
      LETSENCRYPT_HOST: strax.indexer.blockcore.net
      LETSENCRYPT_EMAIL: admin@blockcore.net
      ASPNETCORE_URLS: https://*:9910
    command: ["--chain=STRAX"]
    restart: unless-stopped
    depends_on:
        - mongo
        - chain

  chain:
    container_name: strax-chain
    image: blockcore/node-strax:1.0.29
    command: ["-server=1", "-txindex=1", "-iprangefiltering=0", "-rpcallowip=192.168.0.0/8", "-rpcallowip=172.0.0.0/8", "-rpcbind=0.0.0.0", "-apiuri=http://0.0.0.0:17103", "-rpcuser=rpcuser", "-rpcpassword=rpcpassword"]
    restart: unless-stopped
    stop_grace_period: 15m
    volumes:
      - blockchain:/root/.blockcore
    ports:
      - 17105:17105 # Make this a public node.

  mongo:
    container_name: strax-mongo
    image: mongo:3.6.18
    command: "--wiredTigerCacheSizeGB 1.5"
    mem_limit: 1500m
    restart: unless-stopped
    stop_grace_period: 5m
    volumes:
      - database:/data/db
      - database:/data/configdb

  tipbot:
    container_name: strax-tipbot
    image: blockcore/tipbot:0.0.3
    env_file:
      - tipbot.env
    command: ["--chain=STRAX"]
    restart: unless-stopped
    depends_on:
        - tipbot-database
        - tipbot-chain
    
  tipbot-chain:
    container_name: strax-tipbot-chain
    image: blockcore/node-strax:1.0.29
    command: ["-server=1", "-txindex=0", "-iprangefiltering=0", "-rpcallowip=192.168.0.0/8", "-rpcallowip=172.0.0.0/8", "-rpcbind=0.0.0.0", "-apiuri=http://0.0.0.0:17103", "-rpcuser=rpcuser", "-rpcpassword=rpcpassword"]
    restart: unless-stopped
    stop_grace_period: 15m
    volumes:
      - tipbot-blockchain:/root/.blockcore

  tipbot-database:
    container_name: strax-tipbot-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    env_file:
      - tipbot.env
    environment:
      ACCEPT_EULA: "Y"
    restart: unless-stopped
    volumes:
      - tipbot-database:/var/opt/mssql
