version: "2.4"

volumes:
  database:
    name: swap-db

services:  
  blockcore-swaps:
    container_name: blockcore-atomicswaps
    image: blockcore/atomicswaps:0.0.18
    mem_limit: 1024m
    cpus: 0.200
    environment:
      VIRTUAL_HOST: swap.blockcore.net
      VIRTUAL_PORT: 5500
      VIRTUAL_PROTO: http
      VIRTUAL_NETWORK: proxy
      LETSENCRYPT_HOST: swap.blockcore.net
      LETSENCRYPT_EMAIL: admin@blockcore.net
      ASPNETCORE_URLS: http://+:5500
      Logging__LogLevel__Default: Debug
      DataConfig__UseDefaultPath: "true"
    restart: unless-stopped
    #ports:
      #- "5500:5500"
    volumes:
      - database:/root/.atomicswaps
    networks:
      - proxy
networks:
  proxy:
    external: true
    name: proxy
