version: "3.7"

services:

  explorer:
    container_name: city-explorer
    image: blockcore/explorer:0.0.4
    environment:
      VIRTUAL_HOST: city.explorer.blockcore.net
      LETSENCRYPT_HOST: city.explorer.blockcore.net
      LETSENCRYPT_EMAIL: admin@blockcore.net
    command: ["--chain=CITY"]
    restart: always
    ports: 
        - "9911:9911"