version: "3.7"

volumes:
  database:
    name: city-db
  blockchain:
    name: city-data

services:

  indexer:
    container_name: city-indexer
    networks:
      indexer:
        ipv4_address: 172.16.10.10
    image: blockcore/indexer:0.0.2
    environment:
      - VIRTUAL_HOST=city.indexer.blockcore.net
    command: ["--chain=CITY"]
    restart: always
    stop_grace_period: 5m
    ports: 
        - "9910:9910"
    depends_on:
        - mongo
        - chain

  chain:
    container_name: city-chain
    image: citychain/citychain
    command: ["-server=1", "-txindex=1", "-rpcallowip=172.16.10.10", "-rpcbind=city-chain", "-apiuri=http://0.0.0.0:4335", "-rpcuser=rpcuser", "-rpcpassword=rpcpassword"]
    restart: always
    stop_grace_period: 15m
    networks:
      - indexer
    volumes:
      - blockchain:/root/.citychain

  mongo:
    container_name: city-mongo
    image: mongo:3.4
    restart: always
    stop_grace_period: 5m
    networks:
      - indexer
    volumes:
      - database:/data/db
      - database:/data/configdb

networks:
  indexer:
    name: city-network
    ipam:
      config:
        - subnet: 172.16.10.0/28