version: "2.4"

volumes:
  database:
    name: city-db
  blockchain:
    name: city-data
  tipbot-blockchain:
    name: city-tipbot-data
  tipbot-database:
    name: city-tipbot-db

services:

  bwsnode:
    container_name: city-chain-bws-node
    image: blockcore-bws-city
    command: ["node"]
    environment:
      VIRTUAL_HOST: city.api.blockcore.net
      VIRTUAL_PORT: 3000
      VIRTUAL_NETWORK: proxy
      LETSENCRYPT_HOST: city.api.blockcore.net
      LETSENCRYPT_EMAIL: admin@blockcore.net
      DB_HOST: city-mongo
    restart: always
    depends_on:
        - mongo
        - chain
    ports:
      #- 8100:8100
      - 3000:3000
    env_file:
      - bws.env

  bwsapi:
    # build: .
    tty: true
    container_name: city-chain-bws-api
    image: blockcore-bws-city
    command: ["bws:start"]
    environment:
      VIRTUAL_HOST: city.bws.blockcore.net
      VIRTUAL_PORT: 3232
      VIRTUAL_NETWORK: proxy
      LETSENCRYPT_HOST: city.bws.blockcore.net
      LETSENCRYPT_EMAIL: admin@blockcore.net
      DB_HOST: city-mongo
    depends_on:
        - mongo
        - chain
    ports:
      - 3232:3232
    env_file:
      - bws.env

  bwsinsight:
    container_name: city-chain-bws-insight
    image: blockcore-bws-city
    command: ["insight"]
    environment:
      VIRTUAL_HOST: city.insight.blockcore.net
      VIRTUAL_PORT: 8100
      VIRTUAL_NETWORK: proxy
      LETSENCRYPT_HOST: city.insight.blockcore.net
      LETSENCRYPT_EMAIL: admin@blockcore.net
      DB_HOST: city-mongo
    restart: always
    depends_on:
        - mongo
    ports:
      - 8100:8100
    env_file:
      - bws.env

  explorer:
    container_name: city-explorer
    image: blockcore/explorer:0.1.7
    environment:
      VIRTUAL_HOST: city.explorer.blockcore.net,explorer.city-chain.org
      VIRTUAL_PORT: 9911
      VIRTUAL_NETWORK: proxy
      LETSENCRYPT_HOST: city.explorer.blockcore.net,explorer.city-chain.org
      LETSENCRYPT_EMAIL: admin@blockcore.net
    command: ["--chain=CITY"]
    restart: always

  indexer:
    container_name: city-indexer
    image: blockcore/indexer:0.1.8
    environment:
      VIRTUAL_HOST: city.indexer.blockcore.net,indexer.city-chain.org
      VIRTUAL_PORT: 9910
      VIRTUAL_NETWORK: proxy
      LETSENCRYPT_HOST: city.indexer.blockcore.net,indexer.city-chain.org
      LETSENCRYPT_EMAIL: admin@blockcore.net
      ASPNETCORE_URLS: https://*:9910
    command: ["--chain=CITY"]
    restart: always
    depends_on:
        - mongo
        - chain

  chain:
    container_name: city-chain
    image: blockcore/node-city:1.0.20
    command: ["-server=1", "-txindex=1", "-iprangefiltering=0", "-rpcallowip=172.0.0.0/8", "-rpcbind=0.0.0.0", "-apiuri=http://0.0.0.0:4335", "-rpcuser=rpcuser", "-rpcpassword=rpcpassword"]
    restart: always
    stop_grace_period: 15m
    volumes:
      - blockchain:/root/.blockcore
    ports:
      - 4333:4333 # Make this a public node.

  mongo:
    container_name: city-mongo
    image: mongo:3.6.18
    command: "--wiredTigerCacheSizeGB 0.35"
    mem_limit: 350m
    restart: always
    stop_grace_period: 5m
    volumes:
      - database:/data/db
      - database:/data/configdb

  tipbot:
    container_name: city-tipbot
    image: blockcore/tipbot:0.0.3
    env_file:
      - tipbot.env
    command: ["--chain=CITY"]
    restart: always
    depends_on:
        - tipbot-database
        - tipbot-chain
    
  tipbot-chain:
    container_name: city-tipbot-chain
    image: blockcore/node-city:1.0.20
    command: ["-server=1", "-txindex=0", "-rpcallowip=172.0.0.0/8", "-rpcbind=0.0.0.0", "-apiuri=http://0.0.0.0:4335", "-rpcuser=rpcuser", "-rpcpassword=rpcpassword"]
    restart: always
    stop_grace_period: 15m
    volumes:
      - tipbot-blockchain:/root/.blockcore

  tipbot-database:
    container_name: city-tipbot-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    env_file:
      - tipbot.env
    environment:
      ACCEPT_EULA: "Y"
    restart: always
    volumes:
      - tipbot-database:/var/opt/mssql
