version: "2.4"

volumes:
  database:
    name: city-db
  blockchain:
    name: city-data
  tipbot-blockchain:
    name: city-tipbot-data
  tipbot-database:
    name: city-tipbot-db

services:

  explorer:
    container_name: city-explorer
    image: blockcore/explorer:0.1.7
    environment:
      VIRTUAL_HOST: city.explorer.blockcore.net,explorer.city-chain.org
      VIRTUAL_PORT: 9911
      VIRTUAL_NETWORK: proxy
      LETSENCRYPT_HOST: city.explorer.blockcore.net,explorer.city-chain.org
      LETSENCRYPT_EMAIL: admin@blockcore.net
    command: ["--chain=CITY"]
    restart: always

  indexer:
    container_name: city-indexer
    image: blockcore/indexer:0.1.5
    environment:
      VIRTUAL_HOST: city.indexer.blockcore.net,indexer.city-chain.org
      VIRTUAL_PORT: 9910
      VIRTUAL_NETWORK: proxy
      LETSENCRYPT_HOST: city.indexer.blockcore.net,indexer.city-chain.org
      LETSENCRYPT_EMAIL: admin@blockcore.net
      ASPNETCORE_URLS: https://*:9910
    command: ["--chain=CITY"]
    restart: always
    depends_on:
        - mongo
        - chain

  chain:
    container_name: city-chain
    image: blockcore/node-city:1.0.16
    command: ["-server=1", "-txindex=1", "-rpcallowip=172.0.0.0/8", "-rpcbind=0.0.0.0", "-apiuri=http://0.0.0.0:4335", "-rpcuser=rpcuser", "-rpcpassword=rpcpassword"]
    restart: always
    stop_grace_period: 15m
    volumes:
      - blockchain:/root/.blockcore
    ports:
      - 4333:4333 # Make this a public node.

  mongo:
    container_name: city-mongo
    image: mongo:3.6.18
    command: "--wiredTigerCacheSizeGB 0.35"
    mem_limit: 350m
    restart: always
    stop_grace_period: 5m
    volumes:
      - database:/data/db
      - database:/data/configdb

  tipbot:
    container_name: city-tipbot
    image: blockcore/tipbot:0.0.1
    env_file:
      - tipbot.env
    environment:
      TipBot__ApiUrl: http://city-tipbot-chain:4335/
    command: ["--chain=CITY"]
    restart: always
    depends_on:
        - tipbot-database
        - tipbot-chain
    
  tipbot-chain:
    container_name: city-tipbot-chain
    image: blockcore/node-city:1.0.15
    command: ["-server=1", "-txindex=0", "-rpcallowip=172.0.0.0/8", "-rpcbind=0.0.0.0", "-apiuri=http://0.0.0.0:4335", "-rpcuser=rpcuser", "-rpcpassword=rpcpassword"]
    restart: always
    stop_grace_period: 15m
    volumes:
      - tipbot-blockchain:/root/.blockcore

  tipbot-database:
    container_name: city-tipbot-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    env_file:
      - tipbot.env
    environment:
      ACCEPT_EULA: "Y"
    restart: always
    volumes:
      - tipbot-database:/var/opt/mssql
