version: "3.7"

services:

  explorer:
    container_name: city-explorer
    image: blockcore/explorer:0.0.7
    environment:
      VIRTUAL_HOST: city.explorer.blockcore.net,explorer.city-chain.org
      VIRTUAL_PORT: 9911
      VIRTUAL_NETWORK: proxy
      LETSENCRYPT_HOST: city.explorer.blockcore.net,explorer.city-chain.org
      LETSENCRYPT_EMAIL: admin@blockcore.net
    command: ["--chain=CITY"]
    restart: always