version: "2.4"

volumes:
  database:
    name: city-db
  blockchain:
    name: city-data

services:

  indexer:
    container_name: city-indexer
    networks:
      indexer:
        ipv4_address: 172.16.10.10
    image: blockcore/indexer:0.1.5
    environment:
      VIRTUAL_HOST: city.indexer.blockcore.net,indexer.city-chain.org
      VIRTUAL_PORT: 9910
      VIRTUAL_NETWORK: proxy
      LETSENCRYPT_HOST: city.indexer.blockcore.net,indexer.city-chain.org
      LETSENCRYPT_EMAIL: admin@blockcore.net
    command: ["--chain=CITY"]
    restart: always
    depends_on:
        - mongo
        - chain

  chain:
    container_name: city-chain
    image: blockcore/node-city:1.0.15
    command: ["-server=1", "-txindex=1", "-rpcallowip=172.16.10.10", "-rpcbind=city-chain", "-apiuri=http://0.0.0.0:4335", "-rpcuser=rpcuser", "-rpcpassword=rpcpassword"]
    restart: always
    stop_grace_period: 15m
    networks:
      - indexer
    volumes:
      - blockchain:/root/.blockcore
    ports:
      - 4333:4333

  mongo:
    container_name: city-mongo
    image: mongo:3.6.18
    command: "--wiredTigerCacheSizeGB 0.35"
    mem_limit: 350m
    restart: always
    stop_grace_period: 5m
    networks:
      - indexer
    volumes:
      - database:/data/db
      - database:/data/configdb

networks:
  indexer:
    name: city-network
    ipam:
      config:
        - subnet: 172.16.10.0/28