version: "2.4"

volumes:
  database:
    name: city-tipbot-db
  blockchain:
    name: city-tipbot-data

services:

  tipbot:
    container_name: city-indexer
    image: blockcore/tipbot:0.0.1
    env_file:
      - tipbot.env
    command: ["--chain=CITY"]
    restart: always
    depends_on:
        - database
        - chain

  chain:
    container_name: city-tipbot-chain
    image: blockcore/node-city:1.0.15
    command: ["-server=1", "-txindex=0", "-rpcallowip=127.0.0.1", "-rpcbind=city-tipbot-chain", "-apiuri=http://0.0.0.0:4335", "-rpcuser=rpcuser", "-rpcpassword=rpcpassword"]
    restart: always
    stop_grace_period: 15m
    volumes:
      - blockchain:/root/.blockcore
    ports:
      - 127.0.0.1:4333:4333 # P2P - Only expose these during local test and development, not needed for production.
      - 127.0.0.1:4334:4334 # RPC - Only expose these during local test and development, not needed for production.
      - 127.0.0.1:4335:4335 # API - Only expose these during local test and development, not needed for production.

  database:
    container_name: city-tipbot-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    env_file:
      - tipbot.env
    environment:
      ACCEPT_EULA: "Y"
    restart: always
    volumes:
      - database:/var/opt/mssql
    ports:
      - 14330:1433 # Only expose these during local test and development, not needed for production.
