version: "2.4"

services:

  explorer:
    container_name: x42-explorer
    image: blockcore/explorer:0.1.7
    environment:
      VIRTUAL_HOST: x42.explorer.blockcore.net
      VIRTUAL_PORT: 9911
      VIRTUAL_NETWORK: proxy
      LETSENCRYPT_HOST: x42.explorer.blockcore.net
      LETSENCRYPT_EMAIL: admin@blockcore.net
    command: ["--chain=X42"]
    restart: always